#!/bin/bash
set -e

# Auto-Build Environment Setup
# Generated by Planner Agent

echo "======================================="
echo "Starting Development Environment"
echo "======================================="

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${BLUE}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Ensure directories exist
mkdir -p /data/incoming /reports /logs
chmod 777 /data/incoming /reports /logs

echo -e "${YELLOW}Starting FastAPI web server...${NC}"
cd /home/chris/Documents/Projects/RecilienceScan && uvicorn app.web.main:app --host 0.0.0.0 --port 8080 --reload &
WEB_PID=$!
wait_for_service 8080 "FastAPI Web Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo -e "${BLUE}======================================="
echo -e "Environment Ready!"
echo -e "=======================================${NC}"
echo ""
echo -e "${GREEN}Services:${NC}"
echo -e "  Backend:  http://localhost:8080"
echo ""
echo -e "${YELLOW}Button Flows to Fix:${NC}"
echo -e "  1. Upload Data (Fix 405 Method Not Allowed)"
echo -e "  2. Start Ingestion (Fix 404 Not Found)"
echo -e "  3. Generate Reports (Fix JSON response shape)"
echo -e "  4. View Results (Fix 500 errors)"
echo ""
echo -e "${GREEN}API Endpoints:${NC}"
echo -e "  Upload: POST /upload"
echo -e "  Ingestion: POST /run/ingest"
echo -e "  Reports: GET /reports"
echo -e "  Runs: GET /runs"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo -e "  - Run implementation_plan.json to see all subtasks"
echo -e "  - Fix button flows in sequence or parallel"
echo -e "  - Validate all flows work end-to-end"
echo ""
echo -e "${GREEN}Docker Note:${NC} Ensure /data/incoming, /reports, /logs directories exist"
echo ""
echo -e "${BLUE}=======================================${NC}"
echo -e "${BLUE}To stop services:${NC}"
echo -e "${BLUE}=======================================${NC}"
echo -e "kill $WEB_PID"
echo ""

# Keep script running to maintain services
wait $WEB_PID